server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: careerconnect-backend
  
  cache:
    type: simple

# Firebase Configuration (Development)
firebase:
  service-account-key: classpath:serviceAccountKey.json
  database-url: ${FIREBASE_DATABASE_URL:https://ruvaa-cbcaa-default-rtdb.asia-southeast1.firebasedatabase.app/}
  project-id: ${FIREBASE_PROJECT_ID:ruvaa-cbcaa}

# Google Gemini AI Configuration (Development)
gemini:
  api-key: ${GEMINI_API_KEY:AIzaSyCGo2KpKAMGU7b52skjDvAiFd6CE-v7Ohs}
  base-url: https://generativelanguage.googleapis.com/v1beta
  model: gemini-1.5-flash
  max-tokens: 2048
  temperature: 0.7
  rate-limit:
    requests-per-minute: 20
    burst-capacity: 5

# Security Configuration
jwt:
  secret: ruvaaDevSecretKeyForJWTTokenGenerationAndValidation123456789
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days

# Rate Limiting (Relaxed for development)
rate-limiting:
  enabled: false
  requests-per-minute: 1000
  burst-capacity: 100

# Monitoring (Development)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Logging (Development)
logging:
  level:
    com.ruvaa: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.google.cloud.firestore: DEBUG
    com.google.firebase: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"

# Development specific
debug: true
