server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
  compression:
    enabled: true
    min-response-size: 1024
  http2:
    enabled: true

spring:
  application:
    name: careerconnect-backend
  
  profiles:
    active: prod
    

  security:
    require-ssl: true

  cache:
    type: redis
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms

# Firebase Configuration
firebase:
  service-account-key: ${FIREBASE_SERVICE_ACCOUNT_KEY}
  database-url: ${FIREBASE_DATABASE_URL}
  project-id: ${FIREBASE_PROJECT_ID}

# Google Gemini AI Configuration
gemini:
  api-key: ${GEMINI_API_KEY}
  base-url: https://generativelanguage.googleapis.com/v1beta
  model: gemini-1.5-pro
  max-tokens: 2048
  temperature: 0.7
  rate-limit:
    requests-per-minute: 60
    burst-capacity: 10

# Security Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days

# Rate Limiting
rate-limiting:
  enabled: true
  requests-per-minute: 100
  burst-capacity: 20

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

# Logging
logging:
  level:
    com.ruvaa: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"
  file:
    name: logs/careerconnect.log
    max-size: 100MB
    max-history: 30

# Indian Market Specific Configuration
indian-market:
  salary:
    currency: INR
    unit: LPA
  regions:
    - Bangalore
    - Hyderabad
    - Mumbai
    - Chennai
    - Pune
    - Delhi
    - Kolkata
    - Ahmedabad
  college-tiers:
    tier1:
      - IIT
      - IIM
      - BITS
      - NIT
    tier2:
      - State Universities
      - Private Engineering Colleges
    tier3:
      - Regional Colleges
      - Local Universities

# Internationalization
spring.messages:
  basename: messages
  encoding: UTF-8
  cache-duration: 3600